services:
  ac-app-2:
    container_name: ac-app-2
    build: .
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    runtime: nvidia   # This line was added
    environment:
      - NVIDIA_VISIBLE_DEVICES=all   # This line was added